name: test-workflow
on:
  # when any branch in the repository is pushed
  push:
  # when a pull request is created
  pull_request:
  # when manually triggered to run
  workflow_dispatch:
  # when scheduled
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  # run tests
  test:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
      # do not cancel any jobs when a single job fails
      fail-fast: false
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir --requirement requirements-dev.txt

      - name: Run code linting checks
        run: make ci-lint

      - name: Run tests with code coverage
        run: make coverage

      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }} on ${{ matrix.os }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io when all parallel jobs finished
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip install --no-cache-dir --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
